###
#   Database Settings
###
spring:
  datasource:
    url: jdbc:h2:mem:crawler;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true

###
#   H2 Settings
###
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: true
###
#   mail Settings
###
  spring:
    mail:
      host: smtp.gmail.com
      port: 587
      username: ${username}
      password: ${password}
      protocol: smtp
      tls: true
      properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com